<?php

namespace Database\Seeds\Production;

use App\Data\Models\Site;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;

class LinkedInPickupRequestGlobalAddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $linkedin = Site::where('code', '=', 'linkedin')->first();

        DB::table('pickup_request_address')->insert([
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Edifício Eldorado Business Tower',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Edifício Eldorado Business Tower, Avenida Nações Unidas'),
                'contact_address_2' => Crypt::encrypt('Number 8501, Office 201, Floors 20 & 23'),
                'contact_city' => 'São Paulo',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Brazil',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Al. Araguaia 3641',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Al. Araguaia 3641'),
                'contact_address_2' => Crypt::encrypt('Tamboré, Barueri'),
                'contact_city' => 'Sao Paulo',
                'contact_state' => '',
                'contact_zip' => '06455-000',
                'contact_country' => 'Brazil',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 250 Yonge St., Suites 2500 & 2600',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('250 Yonge St.'),
                'contact_address_2' => Crypt::encrypt('Suites 2500 & 2600'),
                'contact_city' => 'Toronto',
                'contact_state' => 'ON',
                'contact_zip' => 'M5B 2L7',
                'contact_country' => 'Canada',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Level 20, 60 City Road',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Level 20'),
                'contact_address_2' => Crypt::encrypt('60 City Road'),
                'contact_city' => 'Southbank, Melbourne',
                'contact_state' => 'Victoria',
                'contact_zip' => '3006',
                'contact_country' => 'Australia',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Levels 8 & 9, 1 Martin Place',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Levels 8 & 9'),
                'contact_address_2' => Crypt::encrypt('1 Martin Place'),
                'contact_city' => 'Sydney',
                'contact_state' => 'NSW',
                'contact_zip' => '2000',
                'contact_country' => 'Australia',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 639 Gardeners Rd',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('639 Gardeners Rd'),
                'contact_address_2' => Crypt::encrypt('Unit B'),
                'contact_city' => 'Mascot',
                'contact_state' => 'NSW',
                'contact_zip' => '2020',
                'contact_country' => 'Australia',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Jiaming Center',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Jiaming Center, No. 27, East Third Ring Road'),
                'contact_address_2' => Crypt::encrypt('Units 01 & 02, Level 11, Tower B'),
                'contact_city' => 'Beijing ',
                'contact_state' => '',
                'contact_zip' => '100020',
                'contact_country' => 'China',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Hysan Place',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Hysan Place'),
                'contact_address_2' => Crypt::encrypt('38th Floor, 500 Hennessy Road'),
                'contact_city' => 'Causeway Bay',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Hong Kong',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 17/F Global Gateway',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('17/F Global Gateway'),
                'contact_address_2' => Crypt::encrypt('168 Yeung Uk Road'),
                'contact_city' => 'Tsuen Wan New Town',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Hong Kong',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1/F Kerry Warehouse',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1/F Kerry Warehouse'),
                'contact_address_2' => Crypt::encrypt('3 Shing Yiu Street'),
                'contact_city' => 'Kwai Chung',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Hong Kong',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn- 7th & 8th floor, Tower A',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('7th & 8th floor, Tower A, Global Technology Park'),
                'contact_address_2' => Crypt::encrypt('Devarabisanahalli, Outer Ring Road'),
                'contact_city' => 'Bangalore',
                'contact_state' => '',
                'contact_zip' => '560103',
                'contact_country' => 'India',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Maker Maxity, 3 North Avenue, 4th Floor',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Maker Maxity, 3 North Avenue, 4th Floor'),
                'contact_address_2' => Crypt::encrypt('Bandra-Kula Complex, Bandra (East)'),
                'contact_city' => 'Mumbai',
                'contact_state' => '',
                'contact_zip' => '400051',
                'contact_country' => 'India',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 17th Floor, Tower – C',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('17th Floor, Tower – C, Building # 5 ( Cyber Terraces )'),
                'contact_address_2' => Crypt::encrypt('DLF Cyber City'),
                'contact_city' => 'Gurgaon',
                'contact_state' => 'Haryana',
                'contact_zip' => '122002',
                'contact_country' => 'India',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Tata Mumbai IDC',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Tata Mumbai IDC'),
                'contact_address_2' => Crypt::encrypt('6th Floor'),
                'contact_city' => 'Prabahdevi, Mumbai (MH)',
                'contact_state' => '',
                'contact_zip' => '400028',
                'contact_country' => 'India',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Marunouchi Building',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Marunouchi Building'),
                'contact_address_2' => Crypt::encrypt('4 -1 Marunouchi, Chiyoda-ku, 34th Floor, Office 7'),
                'contact_city' => 'Tokyo',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Japan',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Shanghai International Commerce Centre',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Shanghai International Commerce Centre'),
                'contact_address_2' => Crypt::encrypt('Two ICC, Units 2207-09, 22/F, Huaihai Road West Section'),
                'contact_city' => 'Xuhui District, Shanghai',
                'contact_state' => '',
                'contact_zip' => '200231',
                'contact_country' => 'China',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 29A International Business Park',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('29A International Business Park'),
                'contact_address_2' => Crypt::encrypt(''),
                'contact_city' => 'Jurong',
                'contact_state' => '',
                'contact_zip' => '609934',
                'contact_country' => 'Singapore',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 10 Marina Boulevard',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('10 Marina Boulevard'),
                'contact_address_2' => Crypt::encrypt('Marina Bay Financial Centre Tower 2, Floors 29 and 30'),
                'contact_city' => 'Singapore',
                'contact_state' => '',
                'contact_zip' => '18983',
                'contact_country' => 'Singapore',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn -51 Serangoon North Avenue 4',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('51 Serangoon North Avenue 4'),
                'contact_address_2' => Crypt::encrypt(''),
                'contact_city' => 'Singapore',
                'contact_state' => '',
                'contact_zip' => '555858',
                'contact_country' => 'Singapore',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'Equinix SG3 IBX c/o LinkedIn',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Equinix SG3 IBX c/o LinkedIn'),
                'contact_address_2' => Crypt::encrypt('26A Ayer Rajah Crescent'),
                'contact_city' => 'Singapore',
                'contact_state' => '',
                'contact_zip' => '139963',
                'contact_country' => 'Singapore',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Eggenberger strasse 7',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Eggenberger strasse 7'),
                'contact_address_2' => Crypt::encrypt(''),
                'contact_city' => 'Graz',
                'contact_state' => '',
                'contact_zip' => 'A-8020',
                'contact_country' => 'Austria',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - OIKOS Building',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('OIKOS Building'),
                'contact_address_2' => Crypt::encrypt('37-41 Rue du Rocher, Floors 5, 6 & 7'),
                'contact_city' => 'Paris',
                'contact_state' => '',
                'contact_zip' => '75008',
                'contact_country' => 'France',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn -Hofstatt, 4th Floor',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Hofstatt, 4th Floor'),
                'contact_address_2' => Crypt::encrypt('Sendlingerstrasse 12'),
                'contact_city' => 'München',
                'contact_state' => '',
                'contact_zip' => '80331',
                'contact_country' => 'Germany',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Kleyerstraﬂe 90',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Kleyerstraﬂe 90'),
                'contact_address_2' => Crypt::encrypt(''),
                'contact_city' => 'Frankfurt',
                'contact_state' => '',
                'contact_zip' => '60326',
                'contact_country' => 'Germany',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LInkedIn - Gardner House',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Gardner House'),
                'contact_address_2' => Crypt::encrypt('Wilton Plaza'),
                'contact_city' => 'Wilton Place, Dublin',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Ireland',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn -Wilton Place, Dublin 2',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Wilton Place'),
                'contact_address_2' => Crypt::encrypt(''),
                'contact_city' => 'Dublin 2',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Ireland',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Unit 24 Hume Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Unit 24 Hume Avenue'),
                'contact_address_2' => Crypt::encrypt('Parkwest Business Park'),
                'contact_city' => 'Dublin 12',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Ireland',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'Linkedin - Piazza Sigmund Freud, 1',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Piazza Sigmund Freud, 1'),
                'contact_address_2' => Crypt::encrypt(''),
                'contact_city' => 'Milano',
                'contact_state' => '',
                'contact_zip' => '20154',
                'contact_country' => 'Italy',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Netherlands Branch Office',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Netherlands Branch Office'),
                'contact_address_2' => Crypt::encrypt('Rembrandt Tower, 4th Floor, Amstelplein 1'),
                'contact_city' => 'Amsterdam',
                'contact_state' => '',
                'contact_zip' => '1096 HA',
                'contact_country' => 'Netherlands',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 5 Brewery St.',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('5 Brewery St.'),
                'contact_address_2' => Crypt::encrypt('Kempton Park 1600'),
                'contact_city' => 'Johannesburg',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'South Africa',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Paseo de la Castellana 202',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Paseo de la Castellana 202'),
                'contact_address_2' => Crypt::encrypt('5th floor, 28046'),
                'contact_city' => 'Madrid',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Spain',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Birger Jarlsgatan 25',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Birger Jarlsgatan 25, Osterbotten 8'),
                'contact_address_2' => Crypt::encrypt('11145 Stockholm, 5th Floor, Reception and office'),
                'contact_city' => 'Birger Jarlsgatan 25',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'Sweden',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Business Central Towers - Tower A',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Business Central Towers - Tower A'),
                'contact_address_2' => Crypt::encrypt('8th, 9th & 10th Floor. Dubai Media City'),
                'contact_city' => 'Dubai',
                'contact_state' => '',
                'contact_zip' => '',
                'contact_country' => 'United Arab Emirates',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Castlewood House',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Castlewood House'),
                'contact_address_2' => Crypt::encrypt('77-91 New Oxford Street'),
                'contact_city' => 'London',
                'contact_state' => '',
                'contact_zip' => 'WC1A 1DG',
                'contact_country' => 'United Kindom',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Telehouse International',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Telehouse International, Corporation of Europe'),
                'contact_address_2' => Crypt::encrypt('Coriander Avenue'),
                'contact_city' => 'London',
                'contact_state' => '',
                'contact_zip' => 'E14 2AA',
                'contact_country' => 'United Kingdom',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ]
        ]);

    }
}