<?php

namespace Database\Seeds\Production;

use App\Data\Models\Site;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;

class LinkedInPickupRequestUSAddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $linkedin = Site::where('code', '=', 'linkedin')->first();

        DB::table('pickup_request_address')->insert([
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 43940 Digital Loudoun Plaza',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('43940 Digital Loudoun Plaza'),
                'contact_address_2' => Crypt::encrypt('Building G'),,
                'contact_city' => 'Ashburn',
                'contact_state' => 'VA',
                'contact_zip' => '20147',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 44060 Digital Loudoun Plaza',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('44060 Digital Loudoun Plaza'),
                'contact_address_2' => Crypt::encrypt('Building K'),,
                'contact_city' => 'Ashburn',
                'contact_state' => 'VA',
                'contact_zip' => '20147',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 43780 Digital Loudoun Plaza',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('43780 Digital Loudoun Plaza'),
                'contact_address_2' => Crypt::encrypt('Building H'),,
                'contact_city' => 'Ashburn',
                'contact_state' => 'VA',
                'contact_zip' => '20147',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 950 E Collins Boulevard',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('950 E Collins Boulevard'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Richardson',
                'contact_state' => 'TX',
                'contact_zip' => '75081',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1210 Integrity Drive',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1210 Integrity Drive'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Richardson',
                'contact_state' => 'TX',
                'contact_zip' => '75081',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1725 Comstock Street',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1725 Comstock Street'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Santa Clara',
                'contact_state' => 'CA',
                'contact_zip' => '95054',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 21515 Northwest Evergreen Parkway',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('21515 Northwest Evergreen Parkway'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Hillsboro',
                'contact_state' => 'OR',
                'contact_zip' => '97124',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 700 East Middlefield',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('700 East Middlefield'),
                'contact_address_2' => Crypt::encrypt('Building 2'),,
                'contact_city' => 'Mountain View',
                'contact_state' => 'CA',
                'contact_zip' => '94043',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 700 East Middlefield',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('700 East Middlefield'),
                'contact_address_2' => Crypt::encrypt('Building 3'),,
                'contact_city' => 'Mountain View',
                'contact_state' => 'CA',
                'contact_zip' => '94043',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 700 East Middlefield',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('700 East Middlefield'),
                'contact_address_2' => Crypt::encrypt('Building 4'),,
                'contact_city' => 'Mountain View',
                'contact_state' => 'CA',
                'contact_zip' => '94043',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 222 Second Street',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('222 Second Street'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'San Francisco',
                'contact_state' => 'CA',
                'contact_zip' => '94105',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 605 West Maude Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('605 West Maude Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 580 North Mary Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('580 North Mary Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 580 Pastoria Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('580 Pastoria Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 815 West Maude Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('815 West Maude Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 845 West Maude Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('845 West Maude Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 479 North Pastoria Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('479 North Pastoria Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 880 West Maude Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('880 West Maude Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 950 West Maude Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('950 West Maude Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1000 West Maude Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1000 West Maude Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Sunnyvale',
                'contact_state' => 'CA',
                'contact_zip' => '94085',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Twenty-ninth Street',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Twenty-ninth Street'),
                'contact_address_2' => Crypt::encrypt('Suite 2008'),,
                'contact_city' => 'Boulder',
                'contact_state' => 'CO',
                'contact_zip' => '80301',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 6410 Via Real',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('6410 Via Real'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 6430 Via Real',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('6430 Via Real'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 6450 Via Real',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('6450 Via Real'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 6460 Via Real',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('6460 Via Real'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 6440 Via Real',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('6440 Via Real'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 6420 Via Real',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('6420 Via Real'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1001 Mark Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1001 Mark Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1000 Mark Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1000 Mark Avenue'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 6402 Cindy Lane',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('6402 Cindy Lane'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Carpinteria',
                'contact_state' => 'CA',
                'contact_zip' => '93013',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 525 West Monroe Street',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('525 West Monroe Street'),
                'contact_address_2' => Crypt::encrypt('Suite 400 (4th Floor)'),,
                'contact_city' => 'Chicago',
                'contact_state' => 'IL',
                'contact_zip' => '60661',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1001 Woodward Avenue',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1001 Woodward Avenue'),
                'contact_address_2' => Crypt::encrypt('Suite 500'),,
                'contact_city' => 'Detroit',
                'contact_state' => 'MI',
                'contact_zip' => '48226',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Exec Centre II Building',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Exec Centre II Building'),
                'contact_address_2' => Crypt::encrypt('9101 Western Avenue, Suite 102'),,
                'contact_city' => 'Omaha',
                'contact_state' => 'NE',
                'contact_zip' => '68114',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1000 N. 90th Street',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1000 N. 90th Street'),
                'contact_address_2' => Crypt::encrypt('Suite 105'),,
                'contact_city' => 'Omaha',
                'contact_state' => 'NE',
                'contact_zip' => '68114',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Empire State Building',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Empire State Building'),
                'contact_address_2' => Crypt::encrypt('350 Fifth Avenue (25th Floor)'),,
                'contact_city' => 'New York',
                'contact_state' => 'NY',
                'contact_zip' => '10118',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1133 15th Street NW',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1133 15th Street NW'),
                'contact_address_2' => Crypt::encrypt('Suite 950'),,
                'contact_city' => 'Washington',
                'contact_state' => 'DC',
                'contact_zip' => '20005',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 350 East Cermak Road',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('350 East Cermak Road'),
                'contact_address_2' => Crypt::encrypt('6th Floor, Suite 650'),,
                'contact_city' => 'Chicago',
                'contact_state' => 'IL',
                'contact_zip' => '60616',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 21721 Filigree Court',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('21721 Filigree Court'),
                'contact_address_2' => Crypt::encrypt('Suite B'),,
                'contact_city' => 'Ashburn',
                'contact_state' => 'VA',
                'contact_zip' => '20147',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 21715 Filigree Court',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('21715 Filigree Court'),
                'contact_address_2' => Crypt::encrypt('Building F'),,
                'contact_city' => 'Ashburn',
                'contact_state' => 'VA',
                'contact_zip' => '20147',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 600 West 7th Street',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('600 West 7th Street'),
                'contact_address_2' => Crypt::encrypt('6th Floor'),,
                'contact_city' => 'Los Angeles',
                'contact_state' => 'CA',
                'contact_zip' => '90017',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 9 Great Oaks Boulevard',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('9 Great Oaks Boulevard'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'San Jose',
                'contact_state' => 'CA',
                'contact_zip' => '95119',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 1950 North Stemmons Freeway',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('1950 North Stemmons Freeway'),
                'contact_address_2' => Crypt::encrypt('Suite 1039A'),,
                'contact_city' => 'Dallas',
                'contact_state' => 'TX',
                'contact_zip' => '75207',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - Terremark',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('Terremark'),
                'contact_address_2' => Crypt::encrypt('50 NE 8th Street'),,
                'contact_city' => 'Miami',
                'contact_state' => 'FL',
                'contact_zip' => '33132-1715',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $linkedin->id,
                'name' => 'LinkedIn - 2001 6th Ave',
                'company_name' => 'LinkedIn',
                'company_division' => null,
                'contact_name' => Crypt::encrypt(''),
                'contact_phone_number' => Crypt::encrypt(''),
                'contact_address_1' => Crypt::encrypt('2001 6th Ave'),
                'contact_address_2' => Crypt::encrypt(''),,
                'contact_city' => 'Seattle',
                'contact_state' => 'WA',
                'contact_zip' => '98121',
                'contact_country' => 'USA',
                'contact_cell_number' => Crypt::encrypt(''),
                'contact_email_address' => Crypt::encrypt(''),
                'created_at' => Carbon::now()
            ]
        ]);

    }
}