<?php

namespace Database\Seeds\Development;

use App\Data\Models\Site;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;

class PickupRequestAddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $trinity = Site::where('code', '=', 'trinity')->first();

        DB::table('pickup_request_address')->insert([
            [
                'site_id' => $trinity->id,
                'name' => 'St. Agnes Medical Center',
                'company_name' => 'St. Agnes Medical Center',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1303 E. Herndon Ave'),
                'contact_address_2' => null,
                'contact_city' => 'Fresno',
                'contact_state' => 'CA',
                'contact_zip' => '93720',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Francis Healthcare',
                'company_name' => 'St Francis Healthcare',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('701 N. Clayton St'),
                'contact_address_2' => null,
                'contact_city' => 'Wilmington',
                'contact_state' => 'DE',
                'contact_zip' => '19805',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Holy Cross Hospital',
                'company_name' => 'Holy Cross Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('4725 North Federal Highway'),
                'contact_address_2' => null,
                'contact_city' => 'Ft Lauderdale',
                'contact_state' => 'FL',
                'contact_zip' => '33308',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Joseph\'s Health System',
                'company_name' => 'St Joseph\'s Health System',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1230 Baxter St'),
                'contact_address_2' => null,
                'contact_city' => 'Athens',
                'contact_state' => 'GA',
                'contact_zip' => '30606',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Marys Good Samaritan',
                'company_name' => 'St Marys Good Samaritan',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('5401 Lake Oconee Parkway'),
                'contact_address_2' => null,
                'contact_city' => 'Greensboro',
                'contact_state' => 'GA',
                'contact_zip' => '30642',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Marys Sacred Heart',
                'company_name' => 'St Marys Sacred Heart',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('367 Clear Creek Parkway'),
                'contact_address_2' => null,
                'contact_city' => 'Lavonia',
                'contact_state' => 'GA',
                'contact_zip' => '30553',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Medical Center - Clinton',
                'company_name' => 'Mercy Medical Center - Clinton',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('638 South Bluff Blvd.'),
                'contact_address_2' => null,
                'contact_city' => 'Clinton',
                'contact_state' => 'IA',
                'contact_zip' => '52732',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Medical Center - Dubuque',
                'company_name' => 'Mercy Medical Center - Dubuque',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('250 Mercy Drive'),
                'contact_address_2' => null,
                'contact_city' => 'Dubuque',
                'contact_state' => 'IA',
                'contact_zip' => '52001',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Medical  Center - North Iowa  ',
                'company_name' => 'Mercy Medical  Center - North Iowa  ',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1000 4th Street SW'),
                'contact_address_2' => null,
                'contact_city' => 'Mason City',
                'contact_state' => 'IA',
                'contact_zip' => '50401',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Medical  Center - New Hampton',
                'company_name' => 'Mercy Medical  Center - New Hampton',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('308 North Maple Avenue'),
                'contact_address_2' => null,
                'contact_city' => 'New Hampton',
                'contact_state' => 'IA',
                'contact_zip' => '50659',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Medical Center - Sioux City',
                'company_name' => 'Mercy Medical Center - Sioux City',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('624 Jones Street'),
                'contact_address_2' => null,
                'contact_city' => 'Sioux City',
                'contact_state' => 'IA',
                'contact_zip' => '51102',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Alphonsus Regional Med Center',
                'company_name' => 'St Alphonsus Regional Med Center',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1055 N Curtis'),
                'contact_address_2' => null,
                'contact_city' => 'Boise',
                'contact_state' => 'ID',
                'contact_zip' => '83706',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Alphonsus Health System',
                'company_name' => 'St Alphonsus Health System',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1512 12 Ave Road'),
                'contact_address_2' => null,
                'contact_city' => 'Nampa',
                'contact_state' => 'ID',
                'contact_zip' => '83686',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy  Hospital - Chicago',
                'company_name' => 'Mercy  Hospital - Chicago',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('2525 South Michigan Avenue'),
                'contact_address_2' => null,
                'contact_city' => 'Chicago',
                'contact_state' => 'IL',
                'contact_zip' => '60616',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Loyola University Med Center',
                'company_name' => 'Loyola University Med Center',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('2160 S. 1st Ave., Dock 4'),
                'contact_address_2' => null,
                'contact_city' => 'Maywood',
                'contact_state' => 'IL',
                'contact_zip' => '60153',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Gottlieb Memorial Hospital',
                'company_name' => 'Gottlieb Memorial Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('701 W. North Ave'),
                'contact_address_2' => null,
                'contact_city' => 'Melrose Park',
                'contact_state' => 'IL',
                'contact_zip' => '60160',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Joseph Regional Med Center',
                'company_name' => 'St. Joseph Regional Med Center',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('5215 Holy Cross Parkway'),
                'contact_address_2' => null,
                'contact_city' => 'Mishawaka',
                'contact_state' => 'IN',
                'contact_zip' => '46545',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Joseph Regional Med - Plymouth',
                'company_name' => 'St. Joseph Regional Med - Plymouth',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1915 Lake Avenue'),
                'contact_address_2' => null,
                'contact_city' => 'Plymouth',
                'contact_state' => 'IN',
                'contact_zip' => '46563',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Providence Behavioral Health',
                'company_name' => 'Providence Behavioral Health',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1233 Main Street'),
                'contact_address_2' => null,
                'contact_city' => 'Holyoke',
                'contact_state' => 'MA',
                'contact_zip' => '01040',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Health System',
                'company_name' => 'Mercy Health System',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('271 Carew Street'),
                'contact_address_2' => null,
                'contact_city' => 'Springfield',
                'contact_state' => 'MA',
                'contact_zip' => '01104',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Holy Cross Health - Silver Spring ',
                'company_name' => 'Holy Cross Health - Silver Spring ',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1500 Forest Glen Rd'),
                'contact_address_2' => null,
                'contact_city' => 'Silver Spring',
                'contact_state' => 'MD',
                'contact_zip' => '20910',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Joseph Hospital - Chelsea',
                'company_name' => 'St. Joseph Hospital - Chelsea',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('775 S. Main Street'),
                'contact_address_2' => null,
                'contact_city' => 'Chelsea',
                'contact_state' => 'MI',
                'contact_zip' => '48118',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Health Saint Mary\'s',
                'company_name' => 'Mercy Health Saint Mary\'s',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('200 Jefferson Street, S. E.'),
                'contact_address_2' => null,
                'contact_city' => 'Grand Rapids',
                'contact_state' => 'MI',
                'contact_zip' => '49503',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Saint Joseph Livingston',
                'company_name' => 'Saint Joseph Livingston',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('620 Byron Road'),
                'contact_address_2' => null,
                'contact_city' => 'Howell',
                'contact_state' => 'MI',
                'contact_zip' => '48843',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Trinity Health System Office',
                'company_name' => 'Trinity Health System Office',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('20555 Victor Parkway'),
                'contact_address_2' => null,
                'contact_city' => 'Livonia',
                'contact_state' => 'MI',
                'contact_zip' => '48152',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Mary Mercy - Livonia',
                'company_name' => 'St. Mary Mercy - Livonia',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('36475 Five Mile Road'),
                'contact_address_2' => null,
                'contact_city' => 'Livonia',
                'contact_state' => 'MI',
                'contact_zip' => '48154',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Health - Mercy Campus',
                'company_name' => 'Mercy Health - Mercy Campus',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1500 E. Sherman Blvd.'),
                'contact_address_2' => null,
                'contact_city' => 'Muskegon',
                'contact_state' => 'MI',
                'contact_zip' => '49444',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Health - Hackley Campus',
                'company_name' => 'Mercy Health - Hackley Campus',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1700 Clinton Street'),
                'contact_address_2' => null,
                'contact_city' => 'Muskegon',
                'contact_state' => 'MI',
                'contact_zip' => '49442',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Joseph Mercy Pontiac',
                'company_name' => 'St Joseph Mercy Pontiac',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('44405 Woodward Ave'),
                'contact_address_2' => null,
                'contact_city' => 'Pontiac',
                'contact_state' => 'MI',
                'contact_zip' => '48341',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Joseph Mercy Hospital',
                'company_name' => 'St. Joseph Mercy Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1732 Dove Street'),
                'contact_address_2' => null,
                'contact_city' => 'Port Huron',
                'contact_state' => 'MI',
                'contact_zip' => '48060',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Joseph Mercy Hospital',
                'company_name' => 'St. Joseph Mercy Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('5320 Elliot Drive'),
                'contact_address_2' => null,
                'contact_city' => 'Ypsilanti',
                'contact_state' => 'MI',
                'contact_zip' => '48197',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Our Lady of Lourdes - Camden',
                'company_name' => 'Our Lady of Lourdes - Camden',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1600 Haddon Avenue'),
                'contact_address_2' => null,
                'contact_city' => 'Camden',
                'contact_state' => 'NJ',
                'contact_zip' => '08103',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Michaels Med Center',
                'company_name' => 'St. Michaels Med Center',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('109 University Ave.'),
                'contact_address_2' => null,
                'contact_city' => 'Newark',
                'contact_state' => 'NJ',
                'contact_zip' => '07109',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Francis Medical Center',
                'company_name' => 'St. Francis Medical Center',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('601 Hamilton Ave, TIS 4th Floor'),
                'contact_address_2' => null,
                'contact_city' => 'Trenton',
                'contact_state' => 'NJ',
                'contact_zip' => '08629',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Albany Memorial Hospital',
                'company_name' => 'Albany Memorial Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('600 Northern Boulevard'),
                'contact_address_2' => null,
                'contact_city' => 'Albany',
                'contact_state' => 'NY',
                'contact_zip' => '12204',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Peter\'s Hospital',
                'company_name' => 'St Peter\'s Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('315 S. Manning Blvd'),
                'contact_address_2' => null,
                'contact_city' => 'Albany',
                'contact_state' => 'NY',
                'contact_zip' => '12208',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Joseph\'s Hospital Center',
                'company_name' => 'St Joseph\'s Hospital Center',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('301 Prospect Avenue'),
                'contact_address_2' => null,
                'contact_city' => 'Syracuse',
                'contact_state' => 'NY',
                'contact_zip' => '13203',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Samaritan Hospital',
                'company_name' => 'Samaritan Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('2215 Burdett Avenue'),
                'contact_address_2' => null,
                'contact_city' => 'Troy',
                'contact_state' => 'NY',
                'contact_zip' => '12180',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Mary Hospital',
                'company_name' => 'St Mary Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1300 Massachusetts Avenue'),
                'contact_address_2' => null,
                'contact_city' => 'Troy',
                'contact_state' => 'NY',
                'contact_zip' => '12180',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Alphonsus Health System',
                'company_name' => 'St Alphonsus Health System',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('3325 Pocohontas Rd'),
                'contact_address_2' => null,
                'contact_city' => 'Baker City',
                'contact_state' => 'OR',
                'contact_zip' => '97814',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St Alphonsus Health System',
                'company_name' => 'St Alphonsus Health System',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('351 S.W. 9th St'),
                'contact_address_2' => null,
                'contact_city' => 'Ontario',
                'contact_state' => 'OR',
                'contact_zip' => '97914',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Health System',
                'company_name' => 'Mercy Health System',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1 West Elm Street, Ste. 100'),
                'contact_address_2' => null,
                'contact_city' => 'Conshohocken',
                'contact_state' => 'PA',
                'contact_zip' => '19428',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Fitzgerald Hospital',
                'company_name' => 'Mercy Fitzgerald Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1500 Lansdowne Ave'),
                'contact_address_2' => null,
                'contact_city' => 'Darby',
                'contact_state' => 'PA',
                'contact_zip' => '19023',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'St. Mary\'s Medical Center',
                'company_name' => 'St. Mary\'s Medical Center',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('1201 Langehorne-Newtown Rd'),
                'contact_address_2' => null,
                'contact_city' => 'Langhorne',
                'contact_state' => 'PA',
                'contact_zip' => '19047',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'CHE Trinity Health - East',
                'company_name' => 'CHE Trinity Health - East',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('3805 West Chester Pike'),
                'contact_address_2' => null,
                'contact_city' => 'Newtown Square',
                'contact_state' => 'PA',
                'contact_zip' => '19073',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Mercy Philadelphia Hospital',
                'company_name' => 'Mercy Philadelphia Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('501 S. 54th Street'),
                'contact_address_2' => null,
                'contact_city' => 'Philadelphia',
                'contact_state' => 'PA',
                'contact_zip' => '19143',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ],
            [
                'site_id' => $trinity->id,
                'name' => 'Nazareth Hospital',
                'company_name' => 'Nazareth Hospital',
                'company_division' => null,
                'contact_name' => null,
                'contact_phone_number' => null,
                'contact_address_1' => Crypt::encrypt('2601 Holme Avenue'),
                'contact_address_2' => null,
                'contact_city' => 'Philadelphia',
                'contact_state' => 'PA',
                'contact_zip' => '19152',
                'contact_country' => null,
                'contact_cell_number' => null,
                'contact_email_address' => null,
                'created_at' => Carbon::now()
            ]
        ]);

    }
}